version: '2.4'

services:
  redis:
    image: redis:alpine
    networks:
      - frontend
    healthcheck: 
      test: redis-cli ping

  db:
    image: postgres:9.6
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    networks:
      - backend
    healthcheck:
      test: pg_isready -U postgres -h 127.0.0.0

  vote:
    image: bretfisher/examplevotingapp_vote
    ports:
      - '5000:80'
    networks:
      - frontend
    depends_on:
      redis:
        condition: service_healthy

  result:
    build: 
      context: result
    ports:
      - '5001:80'
    volumes:
      - ./result:/app
    networks:
      - backend
    depends_on:
      db:
        condition: service_healthy


  worker:
    image: bretfisher/examplevotingapp_worker
    networks:
      - frontend
      - backend
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy

networks:
    frontend:
    backend:

volumes:
    db-data:

